// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/addressbook.proto

package com.github.zabetak.protobuf.bugs.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<com.github.zabetak.protobuf.bugs.protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.github.zabetak.protobuf.bugs.protos.Person getPeople(int index);
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<? extends com.github.zabetak.protobuf.bugs.protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.github.zabetak.protobuf.bugs.protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
